# Generated by Django 3.1.4 on 2021-01-02 19:41

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('native_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('categories', models.ManyToManyField(to='atmalblog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atmalblog.language')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atmalblog.series')),
            ],
        ),
        migrations.CreateModel(
            name='PostTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=275)),
                ('content', markdownx.models.MarkdownxField()),
                ('published_date', models.DateField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atmalblog.language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atmalblog.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='atmalblog.series'),
        ),
        migrations.AddConstraint(
            model_name='seriestranslations',
            constraint=models.UniqueConstraint(fields=('series', 'language'), name='unique_series_translation'),
        ),
        migrations.AddConstraint(
            model_name='posttranslations',
            constraint=models.UniqueConstraint(fields=('post', 'language'), name='unique_post_translation'),
        ),
    ]
