# Generated by Django 3.1.4 on 2021-01-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmalblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='ISO-639-1 code', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seriestranslations',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atmalblog.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atmalblog.language')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('category', 'language'), name='unique_category_translation'),
        ),
    ]
