# Generated by Django 3.1.4 on 2021-01-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmalblog', '0002_auto_20210117_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seriestranslations',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
