# Generated by Django 3.1.4 on 2021-01-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmalblog', '0003_auto_20210117_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atmalblog.series'),
        ),
    ]
