# Generated by Django 3.1.4 on 2021-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmalblog', '0005_auto_20210120_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=21),
        ),
    ]
